---
- name: Prepare k0s dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0644"
  with_items:
    - /etc/k0s

- name: Deploy k0s config
  ansible.builtin.template:
    src: k0s.yaml.j2
    dest: /etc/k0s/k0s.yaml
    mode: "0644"

- name: Join worker node
  ansible.builtin.shell: >
    k0s install controller --enable-worker -c /etc/k0s/k0s.yaml
  args:
    creates: /etc/systemd/system/k0scontroller.service

- name: Start and enable k0s controller service
  ansible.builtin.systemd:
    name: k0scontroller.service
    enabled: true
    state: started

- name: Ensure /root/.kube directory exists
  file:
    path: /root/.kube
    state: directory
    mode: '0700'
    owner: root
    group: root

- name: Symlink k0s kubeconfig to /root/.kube/config
  file:
    src: /var/lib/k0s/pki/admin.conf
    dest: /root/.kube/config
    state: link
    force: yes
    owner: root
    group: root
