---
helm_chart_name: ingress-nginx
helm_chart_repo: https://kubernetes.github.io/ingress-nginx
helm_chart_ref: ingress-nginx/ingress-nginx
helm_chart_version: "4.10.0"
helm_chart_namespace: ingress-nginx
helm_chart_values:
  controller:
    kind: DaemonSet
    service:
      enabled: false
    ingressClassResource:
      name: ingress-nginx
      enabled: true
      default: true
      controllerValue: k8s.io/ingress-nginx
    hostPort:
      enabled: true
      ports:
        http: 30080
        https: 30443
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

