---
nginx_ingress_values:
  controller:
    kind: DaemonSet
    service:
      enabled: false
    ingressClassResource:
      name: ingress-nginx
      enabled: true
      default: true
      controllerValue: k8s.io/ingress-nginx
    hostPort:
      enabled: true
      ports:
        http: 30080
        https: 30443
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

