name: Build Ostree Container Image
on:
  schedule:
    - cron: '00 8 * * 1'
  push:
    branches: [ '*' ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: fedora:latest
      options: --privileged
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Build
        env:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  
          password_rw: ${{ secrets.GH_TOKEN_RW }} 
          image: ${{ github.repository }}
          tag: ${{ github.ref_name }}
          composefile: "ostree-files/controll-plane.yaml" 
        run: |
          dnf -y --enablerepo=updates-testing install rpm-ostree selinux-policy-targeted skopeo
          mkdir -p repo cache
          skopeo login -u $username -p $password_rw $registry
          ostree init --repo=repo --mode=archive
          rpm-ostree compose image --initialize-mode=if-not-exists \
            --format registry --layer-repo repo --cachedir=cache --copy-retry-times=4 \
            $composefile \
            $registry/$image:$tag