name: Build and Publish Multi-Arch Bootc Image
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU emulation
        uses: docker/setup-qemu-action@v2

      - name: Install Buildah
        uses: redhat-actions/setup-buildah@v2

      - name: Build image (${{ matrix.arch }})
        run: |
          buildah bud --arch ${{ matrix.arch }} -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ matrix.arch }} .

      - name: Push image (${{ matrix.arch }})
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          buildah login -u "${{ github.actor }}" --password-stdin ghcr.io <<< "${CR_TOKEN}"
          buildah push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ matrix.arch }} \
                      docker://ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ matrix.arch }}

  manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Buildah
        uses: redhat-actions/setup-buildah@v2

      - name: Log in to GHCR
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          buildah login -u "${{ github.actor }}" --password-stdin ghcr.io <<< "${CR_TOKEN}"

      - name: Create multi-arch manifest
        run: |
          buildah manifest create ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          buildah manifest add ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest \
                              docker://ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:amd64
          buildah manifest add ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest \
                              docker://ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:arm64

      - name: Push multi-arch manifest
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          buildah push --all ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest \
                       docker://ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
